site_name: Giggle With Python
site_url: https://gauravagarwalgarg.github.io/giggle-with-python/
repo_url: https://github.com/GauravAgarwalGarg/giggle-with-python
theme:
  name: material
  palette:
    - scheme: slate
  features:
    - navigation.sections
    - content.code.copy
    - search.suggest
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables
  - toc:
      permalink: true
